### ISSUE TITLE
Bidirectional MIDI

### ISSUE THREAD

**Issue by Harvie** [jmendeth/trinket-midi-adapter#1]
Can you please make this suitable for bidirectional communication?

**Comment by mildsunrise** [comment]
I'm afraid I can't. When I was making this, I explicitely had to patch SoftwareSerial to remove TX functionality. I don't exactly remember why though.

**Comment by AndreyKudryavtsev** [comment]
Would be awesome to get the midi OUT, even alone.

**Comment by Harvie** [comment]
There has to be way to do this :-)

**Comment by mildsunrise** [comment]
I remember... it was due to the limited interrupts. The Trinket doesn't have enough interrupts to emulate USB *and* a bidirectional Serial Port at the same time.

If you want that, you could buy a [Trinket Pro](https://www.adafruit.com/product/2000) and use [the original MIDI adapter program](https://github.com/jokkebk/TrinketMIDI/blob/master/demo_midiadapter.c). The Trinket Pro contains a *hardware* Serial port, so we only need to emulate USB.
